# Generated by Django 4.2.5 on 2024-02-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
